name = "online-clipboard"
main = "./"
compatibility_date = "2024-01-01"

[site]
bucket = "./.next/static"
exclude = [".next/server/**", ".next/static/development/**"]

[[kv_namespaces]]
binding = "CLIPBOARD_KV"
id = "YOUR_KV_NAMESPACE_ID"

[env.production]
vars = { CONTENT_EXPIRY_MINUTES = "15" }

[[kv_namespaces]]
binding = "CLIPBOARD_KV"
id = "YOUR_PRODUCTION_KV_NAMESPACE_ID"