name = "online-clipboard"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "CLIPBOARD_KV"
id = "49d39547d5504d34b9656ca32965e6a4"

[env.production]
vars = { CONTENT_EXPIRY_MINUTES = "15" }

[[env.production.kv_namespaces]]
binding = "CLIPBOARD_KV"
id = "49d39547d5504d34b9656ca32965e6a4"